insert into Category (dtype, name, description) values ('Category', 'Sprache', 'eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into Category (dtype, name, description) values ('Category', 'Physisch', 'magnis dis parturient montes nascetur');
insert into Category (dtype, name, description) values ('Category', 'Geistig', 'lectus suspendisse potenti in eleifend');
insert into Category (dtype, name, description) values ('Category', 'ÖV', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis');
insert into Category (dtype, name, description) values ('Category', 'Freizeit', 'consequat morbi a ipsum integer');
insert into Category (dtype, name, description) values ('Category', 'Schule', 'aenean fermentum donec ut mauris eget');
insert into Category (dtype, name, description) values ('Category', 'Behörden', 'quisque arcu libero rutrum ac lobortis vel');
insert into Category (dtype, name, description) values ('Category', 'Administrativ', 'ac nulla sed vel enim sit amet nunc viverra');
insert into Category (dtype, name, description) values ('Category', 'Divers', 'sem sed sagittis nam congue risus');
insert into Category (dtype, name, description) values ('Category', 'Sport', 'platea dictumst morbi vestibulum velit id pretium iaculis diam');
