insert into Job_Tags (job_id, tags_name) values (1, 'encryption');
insert into Job_Tags (job_id, tags_name) values (2, 'encryption');
insert into Job_Tags (job_id, tags_name) values (3, 'De-engineered');
insert into Job_Tags (job_id, tags_name) values (4, 'interactive');
insert into Job_Tags (job_id, tags_name) values (5, 'interactive');
insert into Job_Tags (job_id, tags_name) values (6, 'De-engineered');
insert into Job_Tags (job_id, tags_name) values (7, 'conglomeration');
insert into Job_Tags (job_id, tags_name) values (8, 'interactive');
insert into Job_Tags (job_id, tags_name) values (9, 'pricing structure');
insert into Job_Tags (job_id, tags_name) values (10, 'encryption');
insert into Job_Tags (job_id, tags_name) values (11, 'pricing structure');
insert into Job_Tags (job_id, tags_name) values (12, 'De-engineered');
insert into Job_Tags (job_id, tags_name) values (13, 'multimedia');
insert into Job_Tags (job_id, tags_name) values (14, 'Public-key');
insert into Job_Tags (job_id, tags_name) values (15, 'pricing structure');
insert into Job_Tags (job_id, tags_name) values (16, 'knowledge base');
insert into Job_Tags (job_id, tags_name) values (18, 'conglomeration');
insert into Job_Tags (job_id, tags_name) values (19, 'multimedia');
insert into Job_Tags (job_id, tags_name) values (20, 'conglomeration');
insert into Job_Tags (job_id, tags_name) values (21, 'Public-key');
insert into Job_Tags (job_id, tags_name) values (22, 'cohesive');
insert into Job_Tags (job_id, tags_name) values (23, 'De-engineered');
insert into Job_Tags (job_id, tags_name) values (24, 'encryption');
insert into Job_Tags (job_id, tags_name) values (28, 'Public-key');
insert into Job_Tags (job_id, tags_name) values (30, 'knowledge base');
insert into Job_Tags (job_id, tags_name) values (31, 'knowledge base');
insert into Job_Tags (job_id, tags_name) values (32, 'pricing structure');
insert into Job_Tags (job_id, tags_name) values (33, 'De-engineered');
insert into Job_Tags (job_id, tags_name) values (34, 'conglomeration');
insert into Job_Tags (job_id, tags_name) values (35, 'content-based');
insert into Job_Tags (job_id, tags_name) values (36, 'conglomeration');
insert into Job_Tags (job_id, tags_name) values (37, 'Public-key');
insert into Job_Tags (job_id, tags_name) values (38, 'cohesive');
insert into Job_Tags (job_id, tags_name) values (39, 'knowledge base');
insert into Job_Tags (job_id, tags_name) values (40, 'multimedia');
insert into Job_Tags (job_id, tags_name) values (41, 'interactive');
insert into Job_Tags (job_id, tags_name) values (42, 'interactive');
insert into Job_Tags (job_id, tags_name) values (43, 'Public-key');
insert into Job_Tags (job_id, tags_name) values (45, 'interactive');
insert into Job_Tags (job_id, tags_name) values (46, 'pricing structure');
insert into Job_Tags (job_id, tags_name) values (47, 'cohesive');
insert into Job_Tags (job_id, tags_name) values (49, 'content-based');
insert into Job_Tags (job_id, tags_name) values (50, 'conglomeration');