insert into Category (dtype, name, description) values ('Tag', 'De-engineered', 'ante nulla justo aliquam quis turpis eget elit sodales');
insert into Category (dtype, name, description) values ('Tag', 'conglomeration', 'facilisi cras non velit nec nisi vulputate');
insert into Category (dtype, name, description) values ('Tag', 'content-based', 'dapibus duis at velit eu est congue elementum');
insert into Category (dtype, name, description) values ('Tag', 'encryption', 'volutpat quam pede lobortis ligula sit amet eleifend');
insert into Category (dtype, name, description) values ('Tag', 'interactive', 'nam dui proin leo odio porttitor id');
insert into Category (dtype, name, description) values ('Tag', 'Public-key', 'faucibus orci luctus et ultrices');
insert into Category (dtype, name, description) values ('Tag', 'knowledge base', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit');
insert into Category (dtype, name, description) values ('Tag', 'multimedia', 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into Category (dtype, name, description) values ('Tag', 'cohesive', 'turpis enim blandit mi in porttitor pede');
insert into Category (dtype, name, description) values ('Tag', 'pricing structure', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh');