--
-- custom test data
--
insert into User_Tags (helper_email, tags_name) values ('leandro@email.com', 'Abonnement');
insert into User_Tags (helper_email, tags_name) values ('leandro@email.com', 'Zürich');
insert into User_Tags (helper_email, tags_name) values ('leandro@email.com', 'Winterthur');
insert into User_Tags (helper_email, tags_name) values ('hawkeye@email.com', 'Abonnement');
insert into User_Tags (helper_email, tags_name) values ('spidey@email.com', 'Yoga');
insert into User_Tags (helper_email, tags_name) values ('spidey@email.com', 'Kino');
insert into User_Tags (helper_email, tags_name) values ('spidey@email.com', 'Swisspass');

--
-- Mockaroo test data
--
insert into User_Tags (helper_email, tags_name) values ('rsoots2@tripod.com', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('jculverhouse2e@ask.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('mweldrake1k@uol.com.br', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('sshieldona@acquirethisname.com', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('cawtyu@google.es', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('mwonhamy@webmd.com', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('okewish1c@wufoo.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('njolliss2o@chronoengine.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('jdrabblek@upenn.edu', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('mshaylor16@state.gov', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('jriddett2a@wordpress.org', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('tfleischerc@chronoengine.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('ptrippittg@flickr.com', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('pspearettw@weibo.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('epotteridge20@dropbox.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('ntomes2g@wikia.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('ptrippittg@flickr.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('pgeroldini2i@sourceforge.net', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('shofner12@homestead.com', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('hconstance2k@sfgate.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('lcreber1o@last.fm', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('gmackenny1w@purevolume.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('jdrabblek@upenn.edu', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('rsoots2@tripod.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('awilmore18@opera.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('mwonhamy@webmd.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('lcreber1o@last.fm', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('nbonallicki@yandex.ru', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('lparlatt2q@flickr.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('ddunphiem@ucoz.ru', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('jculverhouse2e@ask.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('bmiere24@cnet.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('gmackenny1w@purevolume.com', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('rlavigne0@virginia.edu', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('kbeadles1e@unblog.fr', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('fgrebert2c@amazon.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('fparbrookq@biblegateway.com', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('ddunphiem@ucoz.ru', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('nmalcolm1i@hibu.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('mpatterson1a@miibeian.gov.cn', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('cmewe@jimdo.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('tfleischerc@chronoengine.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('smeekin14@goo.ne.jp', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('hconstance2k@sfgate.com', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('shofner12@homestead.com', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('gchaplain10@scientificamerican.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('jdrabblek@upenn.edu', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('jbohlingolseno@devhub.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('tfleischerc@chronoengine.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('bmiere24@cnet.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('nmalcolm1i@hibu.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('fmenloe1q@dailymail.co.uk', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('mpatterson1a@miibeian.gov.cn', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('jriddett2a@wordpress.org', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('nmalcolm1i@hibu.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('mpatterson1a@miibeian.gov.cn', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('nanton4@amazon.co.jp', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('awilmore18@opera.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('smeekin14@goo.ne.jp', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('mpetkovic6@friendfeed.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('jculverhouse2e@ask.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('jdrabblek@upenn.edu', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('etesmond1y@meetup.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('shofner12@homestead.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('shofner12@homestead.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('gchaplain10@scientificamerican.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('epotteridge20@dropbox.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('pspearettw@weibo.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('shofner12@homestead.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('fparbrookq@biblegateway.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('nmalcolm1i@hibu.com', 'Public-key');
insert into User_Tags (helper_email, tags_name) values ('fmenloe1q@dailymail.co.uk', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('pgeroldini2i@sourceforge.net', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('nanton4@amazon.co.jp', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('gvitall8@booking.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('gchaplain10@scientificamerican.com', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('kkayes1g@seesaa.net', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('fgrebert2c@amazon.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('nteshs@sohu.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('bmiere24@cnet.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('mpetkovic6@friendfeed.com', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('nanton4@amazon.co.jp', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('njolliss2o@chronoengine.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('fparbrookq@biblegateway.com', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('jriddett2a@wordpress.org', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('jbohlingolseno@devhub.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('mweldrake1k@uol.com.br', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('jbohlingolseno@devhub.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('gchaplain10@scientificamerican.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('sshieldona@acquirethisname.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('sshieldona@acquirethisname.com', 'encryption');
insert into User_Tags (helper_email, tags_name) values ('bmiere24@cnet.com', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('smeekin14@goo.ne.jp', 'multimedia');
insert into User_Tags (helper_email, tags_name) values ('pspearettw@weibo.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('hconstance2k@sfgate.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('mwonhamy@webmd.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('jbohlingolseno@devhub.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('epotteridge20@dropbox.com', 'pricing structure');
insert into User_Tags (helper_email, tags_name) values ('lcreber1o@last.fm', 'interactive');
insert into User_Tags (helper_email, tags_name) values ('ddunphiem@ucoz.ru', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('nanton4@amazon.co.jp', 'cohesive');
insert into User_Tags (helper_email, tags_name) values ('okewish1c@wufoo.com', 'content-based');
insert into User_Tags (helper_email, tags_name) values ('nteshs@sohu.com', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('ntunniclisse1s@mozilla.com', 'knowledge base');
insert into User_Tags (helper_email, tags_name) values ('rjaqueme28@businessinsider.com', 'De-engineered');
insert into User_Tags (helper_email, tags_name) values ('smeekin14@goo.ne.jp', 'conglomeration');
insert into User_Tags (helper_email, tags_name) values ('bdubbin26@time.com', 'multimedia');
